export IconHomework from './homework.tsx'
export IconAsk from './ask.tsx'
export IconDiet from './diet.tsx'
export  IconHearts from './hearts.tsx'
export IconSetting from './setting.tsx'
export IconSearch from './search.tsx'
export  IconMicro from "./micro.tsx"
export { default as IconPremium } from './premium.tsx'
export IconScan from './scan.tsx'
export  IconStar  from './star.tsx'
export  IconPremium  from './premium.tsx'
export IconNext from './next.tsx'
export IconLawyer from './lawyer.tsx'
export IconEnglishTeacher from './englishTeacher.tsx'
export IconPsychologist from './psychologist.tsx'
export IconExplore from './explore.tsx'
export IconTask from './task.tsx'
export IconHistory from './history.tsx'
export IconAdjustment from './adjustment.tsx'
export IconDownload from './download.tsx'
export IconSend from './send.tsx'
export IconClear from './clear.tsx'
export IconCopy from './copy.tsx'
export IconShare from './share.tsx'
export IconHearts from './hearts.tsx'

